# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/all
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/basic
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/ts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/egg
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/nuxt
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/react
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/vue
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: npm
    directory: /packages/vue3
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/svelte
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']
