import type { Linter } from 'eslint'
import vuePlugin from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import { GLOB_VUE } from '../constants'

// Get rules from the flat config
const vueFlatRecommended = vuePlugin.configs['flat/recommended']
const vueRecommendedRules = Array.isArray(vueFlatRecommended)
	? vueFlatRecommended.find((c) => c.rules)?.rules || {}
	: {}

/**
 * Vue configuration
 */
export function vue(): Linter.Config[] {
	return [
		{
			name: 'eslint-sets/vue/setup',
			files: [GLOB_VUE],
			languageOptions: {
				parser: vueParser,
				parserOptions: {
					ecmaVersion: 'latest',
					sourceType: 'module',
					extraFileExtensions: ['.vue'],
					ecmaFeatures: {
						jsx: true,
					},
				},
			},
			plugins: {
				vue: vuePlugin,
			},
			rules: {
				...vueRecommendedRules,

				// Vue-specific rules
				'vue/attribute-hyphenation': ['error', 'always'],
				'vue/attributes-order': 'off',
				'vue/block-lang': [
					'error',
					{
						script: {
							lang: ['ts', 'tsx'],
						},
					},
				],
				'vue/block-order': [
					'error',
					{
						order: ['script', 'template', 'style'],
					},
				],
				'vue/component-api-style': ['error', ['script-setup']],
				'vue/component-definition-name-casing': ['error', 'PascalCase'],
				'vue/component-name-in-template-casing': ['error', 'PascalCase'],
				'vue/component-options-name-casing': ['error', 'PascalCase'],
				'vue/custom-event-name-casing': ['error', 'camelCase'],
				'vue/define-emits-declaration': ['error', 'type-based'],
				'vue/define-macros-order': [
					'error',
					{
						order: ['defineProps', 'defineEmits'],
					},
				],
				'vue/define-props-declaration': ['error', 'type-based'],
				'vue/enforce-style-attribute': 'off',
				'vue/first-attribute-linebreak': 'off',
				'vue/html-button-name': 'error',
				'vue/html-closing-bracket-newline': 'off',
				'vue/html-closing-bracket-spacing': 'off',
				'vue/html-comment-content-newline': 'off',
				'vue/html-comment-content-spacing': 'off',
				'vue/html-comment-indent': 'off',
				'vue/html-end-tags': 'error',
				'vue/html-indent': [
					'error',
					2,
					{
						attribute: 1,
						baseIndent: 1,
						closeBracket: 0,
						alignAttributesVertically: true,
						ignores: [],
					},
				],
				'vue/html-quotes': ['error', 'double'],
				'vue/html-self-closing': [
					'error',
					{
						html: {
							void: 'always',
							normal: 'always',
							component: 'always',
						},
						svg: 'always',
						math: 'always',
					},
				],
				'vue/max-attributes-per-line': 'off',
				'vue/max-len': [
					'error',
					{
						code: 120,
						template: 120,
						comments: 120,
					},
				],
				'vue/multi-word-component-names': 'off',
				'vue/multiline-html-element-content-newline': 'off',
				'vue/mustache-interpolation-spacing': ['error', 'always'],
				'vue/new-line-between-multi-line-property': 'off',
				'vue/no-async-in-computed-properties': 'error',
				'vue/no-bare-strings-in-template': 'off',
				'vue/no-boolean-default': 'off',
				'vue/no-builtin-Modifiers': 'error',
				'vue/no-child-content': 'error',
				'vue/no-computed-properties-in-data': 'error',
				'vue/no-constant-condition': 'warn',
				'vue/no-custom-modifiers-on-v-model': 'error',
				'vue/no-deprecated-data-object-declaration': 'error',
				'vue/no-deprecated-destroyed-lifecycle': 'error',
				'vue/no-deprecated-dollar-listeners-api': 'error',
				'vue/no-deprecated-dollar-scopedslots-api': 'error',
				'vue/no-deprecated-events-api': 'error',
				'vue/no-deprecated-filter': 'error',
				'vue/no-deprecated-functional-template': 'error',
				'vue/no-deprecated-html-element-is': 'error',
				'vue/no-deprecated-inline-template': 'error',
				'vue/no-deprecated-props-default-this': 'error',
				'vue/no-deprecated-router-link-tag-prop': 'error',
				'vue/no-deprecated-scope-attribute': 'error',
				'vue/no-deprecated-slot-attribute': 'error',
				'vue/no-deprecated-slot-scope-attribute': 'error',
				'vue/no-deprecated-v-bind-sync': 'error',
				'vue/no-deprecated-v-is': 'error',
				'vue/no-deprecated-v-on-native-modifier': 'error',
				'vue/no-deprecated-v-on-number-modifiers': 'error',
				'vue/no-deprecated-vue-config-keycodes': 'error',
				'vue/no-dupe-keys': 'error',
				'vue/no-dupe-v-else-if': 'error',
				'vue/no-duplicate-attr-inheritance': 'error',
				'vue/no-duplicate-attributes': 'error',
				'vue/no-empty-component-block': 'warn',
				'vue/no-empty-pattern': 'error',
				'vue/no-export-in-script-setup': 'error',
				'vue/no-expose-after-await': 'error',
				'vue/no-extra-parens': 'off',
				'vue/no-invalid-model-keys': 'error',
				'vue/no-irregular-whitespace': 'error',
				'vue/no-lifecycle-after-await': 'error',
				'vue/no-lone-template': 'error',
				'vue/no-loss-of-precision': 'error',
				'vue/no-multi-spaces': 'error',
				'vue/no-multiple-objects-in-class': 'error',
				'vue/no-multiple-slot-args': 'error',
				'vue/no-multiple-template-root': 'off',
				'vue/no-mutating-props': 'error',
				'vue/no-parsing-error': 'error',
				'vue/no-potential-component-option-typo': 'warn',
				'vue/no-ref-as-operand': 'error',
				'vue/no-ref-object-destructure': 'error',
				'vue/no-required-prop-with-default': 'off',
				'vue/no-reserved-component-names': 'error',
				'vue/no-reserved-keys': 'error',
				'vue/no-reserved-props': 'error',
				'vue/no-restricted-block': 'off',
				'vue/no-restricted-call-after-await': 'off',
				'vue/no-restricted-class': 'off',
				'vue/no-restricted-component-names': 'off',
				'vue/no-restricted-component-options': 'off',
				'vue/no-restricted-custom-event': 'off',
				'vue/no-restricted-html-elements': 'off',
				'vue/no-restricted-props': 'off',
				'vue/no-restricted-static-attribute': 'off',
				'vue/no-restricted-syntax': 'off',
				'vue/no-restricted-v-bind': 'off',
				'vue/no-root-v-if': 'warn',
				'vue/no-setup-props-destructure': 'error',
				'vue/no-shared-component-data': 'error',
				'vue/no-side-effects-in-computed-properties': 'error',
				'vue/no-spaces-around-equal-signs-in-attribute': 'error',
				'vue/no-sparse-arrays': 'error',
				'vue/no-static-inline-styles': 'warn',
				'vue/no-template-key': 'error',
				'vue/no-template-shadow': 'error',
				'vue/no-template-target-blank': 'error',
				'vue/no-textarea-mustache': 'error',
				'vue/no-this-in-before-route-enter': 'error',
				'vue/no-undef-components': 'off',
				'vue/no-undef-properties': 'off',
				'vue/no-unsupported-features': 'off',
				'vue/no-unused-components': 'warn',
				'vue/no-unused-properties': 'off',
				'vue/no-unused-refs': 'warn',
				'vue/no-unused-vars': 'warn',
				'vue/no-use-computed-property-like-method': 'error',
				'vue/no-use-v-else-with-v-for': 'error',
				'vue/no-useless-constructor': 'error',
				'vue/no-useless-mustaches': 'error',
				'vue/no-useless-template-attributes': 'error',
				'vue/no-useless-v-bind': 'error',
				'vue/no-v-for-template-key': 'error',
				'vue/no-v-for-template-key-on-child': 'error',
				'vue/no-v-html': 'warn',
				'vue/no-v-model-argument': 'error',
				'vue/no-v-text-v-html-on-component': 'error',
				'vue/no-v-text': 'off',
				'vue/object-shorthand': ['error', 'always'],
				'vue/one-component-per-file': 'error',
				'vue/order-in-components': 'off',
				'vue/padding-line-between-blocks': ['error', 'always'],
				'vue/padding-line-between-tags': 'off',
				'vue/prefer-define-options': 'error',
				'vue/prefer-import-from-vue': 'error',
				'vue/prefer-prop-type-boolean-first': 'error',
				'vue/prefer-separate-static-class': 'error',
				'vue/prefer-template': 'error',
				'vue/prefer-true-attribute-shorthand': 'error',
				'vue/prop-name-casing': ['error', 'camelCase'],
				'vue/quote-props': 'off',
				'vue/require-component-is': 'error',
				'vue/require-default-prop': 'off',
				'vue/require-direct-export': 'error',
				'vue/require-emit-validator': 'off',
				'vue/require-explicit-emits': 'warn',
				'vue/require-expose': 'off',
				'vue/require-macro-variable-name': [
					'error',
					{
						defineProps: 'props',
						defineEmits: 'emit',
						defineSlots: 'slots',
					},
				],
				'vue/require-name-property': 'off',
				'vue/require-prop-comment': 'off',
				'vue/require-prop-type-constructor': 'error',
				'vue/require-prop-types': 'off',
				'vue/require-render-return': 'error',
				'vue/require-slots-as-functions': 'error',
				'vue/require-toggle-inside-transition': 'error',
				'vue/require-typed-object-prop': 'warn',
				'vue/require-typed-ref': 'off',
				'vue/require-v-for-key': 'error',
				'vue/restricted-component-names': 'off',
				'vue/return-in-computed-property': 'error',
				'vue/return-in-emits-validator': 'error',
				'vue/script-indent': 'off',
				'vue/script-setup-uses-vars': 'error',
				'vue/singleline-html-element-content-newline': 'off',
				'vue/slot-name-casing': ['error', 'camelCase'],
				'vue/sort-keys': 'off',
				'vue/static-class-names-order': 'off',
				'vue/style-indent': 'off',
				'vue/template-curly-spacing': 'error',
				'vue/this-in-template': ['error', 'never'],
				'vue/use-v-on-exact': 'error',
				'vue/v-bind-style': ['error', 'shorthand'],
				'vue/v-for-delimiter-style': ['error', 'in'],
				'vue/v-if-else-key': 'error',
				'vue/v-on-event-hyphenation': ['error', 'always'],
				'vue/v-on-function-call': ['error', 'never'],
				'vue/v-on-style': ['error', 'shorthand'],
				'vue/v-slot-style': ['error', 'shorthand'],
				'vue/valid-attribute-name': 'error',
				'vue/valid-define-emits': 'error',
				'vue/valid-define-options': 'error',
				'vue/valid-define-props': 'error',
				'vue/valid-define-slots': 'error',
				'vue/valid-model-definition': 'error',
				'vue/valid-next-tick': 'error',
				'vue/valid-template-root': 'error',
				'vue/valid-v-bind-sync': 'error',
				'vue/valid-v-bind': 'error',
				'vue/valid-v-cloak': 'error',
				'vue/valid-v-else-if': 'error',
				'vue/valid-v-else': 'error',
				'vue/valid-v-for': 'error',
				'vue/valid-v-html': 'error',
				'vue/valid-v-if': 'error',
				'vue/valid-v-is': 'error',
				'vue/valid-v-memo': 'error',
				'vue/valid-v-model': 'error',
				'vue/valid-v-on': 'error',
				'vue/valid-v-once': 'error',
				'vue/valid-v-pre': 'error',
				'vue/valid-v-show': 'error',
				'vue/valid-v-slot': 'error',
				'vue/valid-v-text': 'error',
			},
		},
	]
}
